-- Bảng chức vụ
CREATE TABLE positions (
                           position_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           ten_vi_tri NVARCHAR2(100)
);

-- Bảng nhân viên
CREATE TABLE employees (
                           employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           full_name NVARCHAR2(100),
                           email VARCHAR2(100),
                           gender NVARCHAR2(10),
                           date_of_birth DATE,
                           hire_date DATE,
                           salary NUMBER(10, 2),
                           position_id NUMBER,
                           CONSTRAINT fk_position
                               FOREIGN KEY (position_id)
                                   REFERENCES positions(position_id)
);

-- Dữ liệu bảng positions
INSERT INTO positions (ten_vi_tri) VALUES (N'Kỹ sư phần mềm');
INSERT INTO positions (ten_vi_tri) VALUES (N'Chuyên viên nhân sự');
INSERT INTO positions (ten_vi_tri) VALUES (N'Quản lý dự án');
INSERT INTO positions (ten_vi_tri) VALUES (N'Trưởng phòng CNTT');
INSERT INTO positions (ten_vi_tri) VALUES (N'Kế toán');
INSERT INTO positions (ten_vi_tri) VALUES (N'Thực tập sinh');
INSERT INTO positions (ten_vi_tri) VALUES (N'Nhân viên marketing');
INSERT INTO positions (ten_vi_tri) VALUES (N'Trợ lý giám đốc');
INSERT INTO positions (ten_vi_tri) VALUES (N'Bảo vệ');
INSERT INTO positions (ten_vi_tri) VALUES (N'Nhân viên chăm sóc khách hàng');

-- Dữ liệu bảng employees
INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Nguyen Van A', 'nguyenvana@proton.com', N'Nam', TO_DATE('1990-05-15', 'YYYY-MM-DD'), TO_DATE('2020-06-01', 'YYYY-MM-DD'), 30000000, 1);

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Tran Thi B', 'tranthib@proton.com', N'Nữ', TO_DATE('1993-03-20', 'YYYY-MM-DD'), TO_DATE('2021-01-15', 'YYYY-MM-DD'), 18000000, 2);

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Le Van C', 'levanc@proton.com', N'Nam', TO_DATE('1985-11-30', 'YYYY-MM-DD'), TO_DATE('2018-09-10', 'YYYY-MM-DD'), 35000000, 3);

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Pham Thi D', 'phamthid@proton.com', N'Nữ', TO_DATE('1992-07-25', 'YYYY-MM-DD'), TO_DATE('2019-12-01', 'YYYY-MM-DD'), 28000000, 4);

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Do Van E', 'dovane@proton.com', N'Nam', TO_DATE('1995-04-10', 'YYYY-MM-DD'), TO_DATE('2022-04-01', 'YYYY-MM-DD'), 16000000, 5);

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Hoang Thi F', 'hoangthif@proton.com', N'Nữ', TO_DATE('2000-01-05', 'YYYY-MM-DD'), TO_DATE('2023-02-20', 'YYYY-MM-DD'), 8000000, 6);

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Nguyen Van G', 'nguyenvang@proton.com', N'Nam', TO_DATE('1991-06-18', 'YYYY-MM-DD'), TO_DATE('2021-07-15', 'YYYY-MM-DD'), 19000000, 7);

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Vo Thi H', 'vothih@proton.com', N'Nữ', TO_DATE('1998-09-09', 'YYYY-MM-DD'), TO_DATE('2020-10-10', 'YYYY-MM-DD'), 17000000, 8);

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Pham Van I', 'phamvani@proton.com', N'Nam', TO_DATE('1980-08-08', 'YYYY-MM-DD'), TO_DATE('2010-01-01', 'YYYY-MM-DD'), 10000000, 9);

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Le Thi J', 'lethij@proton.com', N'Nữ', TO_DATE('1994-12-12', 'YYYY-MM-DD'), TO_DATE('2021-05-05', 'YYYY-MM-DD'), 15000000, 10);


SELECT * FROM positions;

SELECT * FROM employees;

-- ===========================
-- I. CÂU HỎI CƠ BẢN (SELECT, WHERE, ORDER BY, LIKE, BETWEEN, IN)
-- ===========================

-- 1. Liệt kê tất cả nhân viên với đầy đủ thông tin

SELECT * FROM employees;

-- 2. Hiển thị tên, giới tính và ngày sinh của các nhân viên nữ
SELECT full_name,gender,date_of_birth FROM employees
WHERE gender = N'Nữ';


-- 3. Tìm những nhân viên có mức lương từ 20 triệu trở lên

SELECT * FROM employees
WHERE salary >= 20000000;

-- 4. Liệt kê nhân viên có tên bắt đầu bằng “Nguyen”

SELECT * FROM employees
WHERE full_name LIKE  'Nguyen%'; --'%' là ký tự đại diện cho bất kỳ chuỗi nào, kể cả chuỗi rỗng.

-- 5. Hiển thị nhân viên có ngày sinh từ 1990 đến 1995

SELECT * FROM employees
WHERE date_of_birth BETWEEN TO_DATE('1990-01-01','YYYY-MM-DD') AND  TO_DATE('1995-12-31','YYYY-MM-DD');


-- 6. Liệt kê nhân viên thuộc các chức vụ có mã là 1, 3 hoặc 5

SELECT * FROM employees
WHERE position_id IN (1,3,5);

-- 7. Sắp xếp danh sách nhân viên theo lương giảm dần

SELECT * FROM employees
ORDER BY salary DESC;

-- ORDER BY được sử dụng trong câu lệnh SELECT để sắp xếp các hàng trong tập kết quả.

-- GROUP BY dùng để nhóm dữ liệu theo một hoặc nhiều cột, thường dùng với các hàm tổng hợp như SUM(), COUNT(), AVG(), MAX(), MIN()...


-- 8. Liệt kê các nhân viên có năm sinh trước 1990

SELECT * FROM employees
WHERE EXTRACT(YEAR FROM date_of_birth) < 1990;

--EXTRACT(YEAR FROM date_of_birth)

--Nếu date_of_birth = '1985-07-21' thì EXTRACT(YEAR FROM date_of_birth) trả về 1985.


-- ===========================
-- II. CÂU HỎI TRUNG BÌNH (JOIN, GROUP BY, HAVING, HÀM TỔNG HỢP)
-- ===========================


-- 1. Liệt kê tên nhân viên, email và tên chức vụ

SELECT e.full_name,e.email, p.ten_vi_tri FROM employees e
JOIN positions p on e.position_id = p.position_id;

-- 2. Tính tổng số nhân viên

SELECT COUNT(*) AS tong_nhan_vien
FROM employees;

-- 3. Tính lương trung bình của nhân viên

SELECT  AVG(salary) AS luong_trung_binh
FROM employees;

-- 5. Tìm chức vụ có nhiều nhân viên nhất

SELECT position_id,COUNT(*) AS so_luong_nv
FROM employees
GROUP BY position_id --Nhóm các nhân viên theo position_id, tức là các nhân viên sẽ được chia thành từng nhóm theo chức vụ của họ.
                     -- Mỗi nhóm sẽ chứa các nhân viên có cùng một position_id.

ORDER BY so_luong_nv DESC --Sắp xếp kết quả nhóm theo số lượng nhân viên (so_luong_nv) từ cao đến thấp. Điều này đảm bảo rằng chức vụ có nhiều nhân viên nhất sẽ đứng ở đầu danh sách.
FETCH FIRST 1 ROWS ONLY;  --Lấy 1 dòng duy nhất từ kết quả sau khi đã sắp xếp. Đây là cách để lấy chức vụ có nhiều nhân viên nhất (vì đã được sắp xếp theo thứ tự giảm dần).


-- 6. Liệt kê chức vụ có lương trung bình trên 15 triệu

SELECT position_id, AVG(salary) AS avg_salary
FROM employees
GROUP BY position_id
HAVING AVG(salary) > 15000000;

-- 7. Tìm nhân viên có lương cao nhất

SELECT * FROM employees
WHERE salary = (SELECT MAX(salary) FROM employees);

-- 8. Tìm nhân viên có ngày vào làm sớm nhất

SELECT * FROM employees
WHERE hire_date = (SELECT MIN(hire_date) FROM employees);

-- ===========================
-- III. CÂU HỎI NÂNG CAO (SUBQUERY, CASE, RANK, UPDATE, DELETE)
-- ===========================

--Subquery (truy vấn con) trong SQL là một truy vấn được lồng bên trong một truy vấn chính (outer query).
-- Nó thường được đặt trong dấu ngoặc () và được sử dụng để trả về dữ liệu mà truy vấn chính sẽ dùng để xử lý tiếp.

-- 1. Nhân viên có lương cao thứ hai
SELECT *
FROM (
         SELECT e.*, DENSE_RANK() OVER (ORDER BY salary DESC) AS xep_hang
         FROM employees e
     ) t --t đằng sau là bí danh (alias) cho subquery (truy vấn con)
WHERE xep_hang = 2;

-- 2. Phân loại nhân viên theo mức lương

SELECT full_name,salary,
       CASE
           WHEN salary > 30000000 THEN 'Cao'
           WHEN salary BETWEEN 15000000 AND 30000000 THEN 'Trung bình'
            ELSE  'Thấp'
            END AS phan_loai


from employees
ORDER BY salary DESC ;

-- 3. Lương trung bình theo giới tính

SELECT gender, AVG(salary) AS avg_salary
FROM employees
GROUP BY gender;

-- 4. Xếp hạng lương của nhân viên

SELECT full_name, salary,
       RANK() OVER ( ORDER BY salary DESC ) AS hang_luong
FROM employees;

-- 5. Nhân viên có lương cao hơn lương trung bình

SELECT * FROM employees
WHERE salary > (SELECT AVG(salary) FROM employees);

-- 6. Tăng 10% lương cho thực tập sinh

SELECT e.employee_id, e.salary, p.ten_vi_tri
FROM employees e
         JOIN positions p ON e.position_id = p.position_id
WHERE p.ten_vi_tri = N'Thực tập sinh';

UPDATE employees
SET salary = salary * 1.1
WHERE position_id IN (SELECT position_id FROM positions WHERE ten_vi_tri = N'Thực tập sinh');


-- 7. Xoá nhân viên lương < 11 triệu và vào làm trước 2023

SELECT e.employee_id, e.salary, p.ten_vi_tri, e.hire_date
FROM employees e
         JOIN positions p ON e.position_id = p.position_id;

DELETE FROM employees
WHERE salary < 11000000
AND hire_date < TO_DATE('2023-01-01','YYYY-MM-DD');


-- 8. Thêm nhân viên mới


SELECT e.employee_id,e.full_name ,e.salary, p.ten_vi_tri, e.hire_date
FROM employees e
         JOIN positions p ON e.position_id = p.position_id;

INSERT INTO employees (full_name, email, gender, date_of_birth, hire_date, salary, position_id)
VALUES ('Tran Van K', 'tranvank@proton.com', N'Nam', TO_DATE('1996-05-01', 'YYYY-MM-DD'),
        TO_DATE('2024-01-15', 'YYYY-MM-DD'), 15000000,
        (SELECT position_id FROM positions WHERE ten_vi_tri = N'Trợ lý giám đốc'));

